name = "ascii-press"
license = "MIT"
licenselink = "https://github.com/bric3/ascii-press/blob/master/LICENSE.md"
description = "Premium Asciidoctor, light or dark theme for software engineers"
tags = ["blog", "highlight.js", "font-awesome", "google analytics", "disqus", "personal", "syntax highlighting", "responsive", "graphcomment", "asciidoctor", "light", "dark-mode"]
features = ["blog", "theme", "highlight.js", "font-awesome", "responsive", "disqus", "graphcomment", "portfolio", "dark-mode", "asciidoctor"]
homepage = "https://github.com/bric3/ascii-press"
min_version = "0.79.0"

[author]
    name = "bric3"
    homepage = "https://bric3.github.io"

# If Porting existing theme
[original]
    author =  "htrn3"
    homepage = "https://htr3n.github.io"
    repo = "https://github.com/htr3n/hyde-hyde"
